version: '3.7'

services:
  api:
    image: "${API_IMAGE}"
    container_name: api
    restart: unless-stopped
    ports:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}

  nginx:
    image: "${NGINX_IMAGE}"
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - api
      - client

  client:
    image: "${CLIENT_IMAGE}"
    container_name: client
    restart: unless-stopped
    ports:
      - 3000
    depends_on:
      - api
